# Generated by Django 5.0.7 on 2024-07-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('gender', models.CharField(max_length=1)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('code', models.CharField(blank=True, max_length=45, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'centre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailReservationSalle',
            fields=[
                ('id_reservation', models.AutoField(primary_key=True, serialize=False)),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('id_salle', models.IntegerField()),
                ('salle', models.CharField(max_length=100)),
                ('financement', models.CharField(max_length=100)),
                ('objet', models.TextField()),
                ('participant', models.IntegerField()),
                ('demandeur', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'v_reservation_salle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Financement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_bailleur', models.CharField(blank=True, max_length=125, null=True, unique=True)),
            ],
            options={
                'db_table': 'financement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fonction', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'fonction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('objet', models.TextField(blank=True, null=True)),
                ('participant', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reservation_salle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_salle', models.CharField(blank=True, max_length=125, null=True, unique=True)),
            ],
            options={
                'db_table': 'salle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(blank=True, max_length=5, null=True, unique=True)),
            ],
            options={
                'db_table': 'services',
                'managed': False,
            },
        ),
    ]
